CREATE TABLE `AssignmentSummary` (
  `DropboxId` bigint NOT NULL,
  `OrgUnitId` int DEFAULT NULL,
  `Name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Category` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Type` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GradeItemId` bigint DEFAULT NULL,
  `PossibleScore` decimal(19,9) DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `DueDate` datetime DEFAULT NULL,
  `IsRestricted` tinyint DEFAULT NULL,
  `IsDeleted` tinyint DEFAULT NULL,
  `TurnItInEnabled` tinyint DEFAULT NULL,
  `IsHidden` tinyint DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  `SubmissionType` varchar(18) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CompletionType` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ResultId` int DEFAULT NULL,
  `CategoryId` bigint DEFAULT NULL,
  `Version` bigint DEFAULT NULL,
  `StartDateAvailabilityType` smallint DEFAULT NULL,
  `EndDateAvailabilityType` smallint DEFAULT NULL,
  `AIUtilization` int DEFAULT NULL,
  UNIQUE KEY `DropboxId` (`DropboxId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `AssignmentSummary_LOAD` (
  `DropboxId` bigint NOT NULL,
  `OrgUnitId` int DEFAULT NULL,
  `Name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Category` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Type` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GradeItemId` bigint DEFAULT NULL,
  `PossibleScore` decimal(19,9) DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `DueDate` datetime DEFAULT NULL,
  `IsRestricted` tinyint DEFAULT NULL,
  `IsDeleted` tinyint DEFAULT NULL,
  `TurnItInEnabled` tinyint DEFAULT NULL,
  `IsHidden` tinyint DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  `SubmissionType` varchar(18) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CompletionType` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ResultId` int DEFAULT NULL,
  `CategoryId` bigint DEFAULT NULL,
  `Version` bigint DEFAULT NULL,
  `StartDateAvailabilityType` smallint DEFAULT NULL,
  `EndDateAvailabilityType` smallint DEFAULT NULL,
  `AIUtilization` int DEFAULT NULL,
  UNIQUE KEY `DropboxId` (`DropboxId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;