CREATE TABLE `ContentObjects` (
  `ContentObjectId` int NOT NULL,
  `OrgUnitId` int DEFAULT NULL,
  `Title` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ContentObjectType` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CompletionType` varchar(7) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ParentContentObjectId` int DEFAULT NULL,
  `Location` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `DueDate` datetime DEFAULT NULL,
  `ObjectId1` int DEFAULT NULL,
  `ObjectId2` int DEFAULT NULL,
  `ObjectId3` int DEFAULT NULL,
  `LastModified` datetime DEFAULT NULL,
  `IsDeleted` tinyint DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  `Depth` int DEFAULT NULL,
  `ToolId` int DEFAULT NULL,
  `IsHidden` tinyint DEFAULT NULL,
  `ResultId` int DEFAULT NULL,
  `DeletedDate` datetime DEFAULT NULL,
  `CreatedBy` int DEFAULT NULL,
  `LastModifiedBy` int DEFAULT NULL,
  `DeletedBy` int DEFAULT NULL,
  UNIQUE KEY `ContentObjectId` (`ContentObjectId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ContentObjects_LOAD` (
  `ContentObjectId` int NOT NULL,
  `OrgUnitId` int DEFAULT NULL,
  `Title` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ContentObjectType` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CompletionType` varchar(7) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ParentContentObjectId` int DEFAULT NULL,
  `Location` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `DueDate` datetime DEFAULT NULL,
  `ObjectId1` int DEFAULT NULL,
  `ObjectId2` int DEFAULT NULL,
  `ObjectId3` int DEFAULT NULL,
  `LastModified` datetime DEFAULT NULL,
  `IsDeleted` tinyint DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  `Depth` int DEFAULT NULL,
  `ToolId` int DEFAULT NULL,
  `IsHidden` tinyint DEFAULT NULL,
  `ResultId` int DEFAULT NULL,
  `DeletedDate` datetime DEFAULT NULL,
  `CreatedBy` int DEFAULT NULL,
  `LastModifiedBy` int DEFAULT NULL,
  `DeletedBy` int DEFAULT NULL,
  UNIQUE KEY `ContentObjectId` (`ContentObjectId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;