CREATE TABLE `DiscussionTopics` (
  `OrgUnitId` int DEFAULT NULL,
  `TopicId` bigint NOT NULL,
  `ForumId` bigint DEFAULT NULL,
  `Name` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Description` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MustPostToParticipate` tinyint DEFAULT NULL,
  `AllowAnon` tinyint DEFAULT NULL,
  `IsHidden` tinyint DEFAULT NULL,
  `RequiresApproval` tinyint DEFAULT NULL,
  `LastPostDate` datetime DEFAULT NULL,
  `LastPostUserId` bigint DEFAULT NULL,
  `NumViews` bigint DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  `IsDeleted` tinyint DEFAULT NULL,
  `DeletedDate` datetime DEFAULT NULL,
  `DeletedByUserId` int DEFAULT NULL,
  `GradeItemId` int DEFAULT NULL,
  `ScoreOutOf` float DEFAULT NULL,
  `ScoreCalculationMethod` varchar(19) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IncludeNonScoredValues` tinyint DEFAULT NULL,
  `Version` bigint DEFAULT NULL,
  `ResultId` int DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `StartDateAvailabilityType` smallint DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `EndDateAvailabilityType` smallint DEFAULT NULL,
  UNIQUE KEY `TopicId` (`TopicId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `DiscussionTopics_LOAD` (
  `OrgUnitId` int DEFAULT NULL,
  `TopicId` bigint NOT NULL,
  `ForumId` bigint DEFAULT NULL,
  `Name` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Description` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MustPostToParticipate` tinyint DEFAULT NULL,
  `AllowAnon` tinyint DEFAULT NULL,
  `IsHidden` tinyint DEFAULT NULL,
  `RequiresApproval` tinyint DEFAULT NULL,
  `LastPostDate` datetime DEFAULT NULL,
  `LastPostUserId` bigint DEFAULT NULL,
  `NumViews` bigint DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  `IsDeleted` tinyint DEFAULT NULL,
  `DeletedDate` datetime DEFAULT NULL,
  `DeletedByUserId` int DEFAULT NULL,
  `GradeItemId` int DEFAULT NULL,
  `ScoreOutOf` float DEFAULT NULL,
  `ScoreCalculationMethod` varchar(19) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IncludeNonScoredValues` tinyint DEFAULT NULL,
  `Version` bigint DEFAULT NULL,
  `ResultId` int DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `StartDateAvailabilityType` smallint DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `EndDateAvailabilityType` smallint DEFAULT NULL,
  UNIQUE KEY `TopicId` (`TopicId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;