CREATE TABLE `GradeObjects` (
  `GradeObjectId` int NOT NULL,
  `OrgUnitId` int DEFAULT NULL,
  `ParentGradeObjectId` int DEFAULT NULL,
  `Name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TypeName` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `IsAutoPointed` tinyint DEFAULT NULL,
  `IsFormula` tinyint DEFAULT NULL,
  `IsBonus` tinyint DEFAULT NULL,
  `MaxPoints` decimal(19,9) DEFAULT NULL,
  `CanExceedMaxGrade` tinyint DEFAULT NULL,
  `ExcludeFromFinalGradeCalc` tinyint DEFAULT NULL,
  `GradeSchemeId` bigint DEFAULT NULL,
  `Weight` decimal(19,9) DEFAULT NULL,
  `NumLowestGradesToDrop` int DEFAULT NULL,
  `NumHighestGradesToDrop` int DEFAULT NULL,
  `WeightDistributionType` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CreatedDate` datetime DEFAULT NULL,
  `ToolName` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AssociatedToolItemId` bigint DEFAULT NULL,
  `LastModified` datetime DEFAULT NULL,
  `ShortName` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GradeObjectTypeId` int DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  `IsDeleted` tinyint DEFAULT NULL,
  `DeletedDate` datetime DEFAULT NULL,
  `DeletedByUserId` int DEFAULT NULL,
  `ResultId` int DEFAULT NULL,
  UNIQUE KEY `GradeObjectId` (`GradeObjectId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `GradeObjects_LOAD` (
  `GradeObjectId` int NOT NULL,
  `OrgUnitId` int DEFAULT NULL,
  `ParentGradeObjectId` int DEFAULT NULL,
  `Name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TypeName` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `IsAutoPointed` tinyint DEFAULT NULL,
  `IsFormula` tinyint DEFAULT NULL,
  `IsBonus` tinyint DEFAULT NULL,
  `MaxPoints` decimal(19,9) DEFAULT NULL,
  `CanExceedMaxGrade` tinyint DEFAULT NULL,
  `ExcludeFromFinalGradeCalc` tinyint DEFAULT NULL,
  `GradeSchemeId` bigint DEFAULT NULL,
  `Weight` decimal(19,9) DEFAULT NULL,
  `NumLowestGradesToDrop` int DEFAULT NULL,
  `NumHighestGradesToDrop` int DEFAULT NULL,
  `WeightDistributionType` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CreatedDate` datetime DEFAULT NULL,
  `ToolName` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AssociatedToolItemId` bigint DEFAULT NULL,
  `LastModified` datetime DEFAULT NULL,
  `ShortName` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GradeObjectTypeId` int DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  `IsDeleted` tinyint DEFAULT NULL,
  `DeletedDate` datetime DEFAULT NULL,
  `DeletedByUserId` int DEFAULT NULL,
  `ResultId` int DEFAULT NULL,
  UNIQUE KEY `GradeObjectId` (`GradeObjectId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;