CREATE TABLE `IntelligentAgentObjects` (
  `AgentId` bigint NOT NULL,
  `OrgUnitId` int DEFAULT NULL,
  `AgentName` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Description` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Enabled` tinyint DEFAULT NULL,
  `SpecificRoles` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LoginConditionEnabled` tinyint DEFAULT NULL,
  `LoginConditionThreshold` int DEFAULT NULL,
  `LoginConditionType` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AccessConditionEnabled` tinyint DEFAULT NULL,
  `AccessConditionThreshold` int DEFAULT NULL,
  `AccessConditionType` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ResultId` bigint DEFAULT NULL,
  `RepeatType` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EmailWhenSatisfied` tinyint DEFAULT NULL,
  `EnableSchedule` tinyint DEFAULT NULL,
  `ScheduleType` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ScheduleRepeatsEvery` int DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `LastModified` datetime DEFAULT NULL,
  `LastModifiedBy` int DEFAULT NULL,
  `IsDeleted` tinyint DEFAULT NULL,
  UNIQUE KEY `AgentId` (`AgentId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `IntelligentAgentObjects_LOAD` (
  `AgentId` bigint NOT NULL,
  `OrgUnitId` int DEFAULT NULL,
  `AgentName` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Description` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Enabled` tinyint DEFAULT NULL,
  `SpecificRoles` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LoginConditionEnabled` tinyint DEFAULT NULL,
  `LoginConditionThreshold` int DEFAULT NULL,
  `LoginConditionType` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AccessConditionEnabled` tinyint DEFAULT NULL,
  `AccessConditionThreshold` int DEFAULT NULL,
  `AccessConditionType` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ResultId` bigint DEFAULT NULL,
  `RepeatType` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EmailWhenSatisfied` tinyint DEFAULT NULL,
  `EnableSchedule` tinyint DEFAULT NULL,
  `ScheduleType` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ScheduleRepeatsEvery` int DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `LastModified` datetime DEFAULT NULL,
  `LastModifiedBy` int DEFAULT NULL,
  `IsDeleted` tinyint DEFAULT NULL,
  UNIQUE KEY `AgentId` (`AgentId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;