CREATE TABLE `QuizObjects` (
  `QuizId` bigint NOT NULL,
  `QuizName` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `QuizDescription` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `QuizCategory` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IsActive` tinyint DEFAULT NULL,
  `OrgUnitId` int DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `DueDate` datetime DEFAULT NULL,
  `CreationDate` datetime DEFAULT NULL,
  `CreatedBy` bigint DEFAULT NULL,
  `LastModified` datetime DEFAULT NULL,
  `LastModifiedBy` bigint DEFAULT NULL,
  `GradeObjectId` bigint DEFAULT NULL,
  `OverallScoreCalculation` varchar(23) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `QuizScoreDenominator` decimal(19,9) DEFAULT NULL,
  `HasPassword` tinyint DEFAULT NULL,
  `IPRestricted` tinyint DEFAULT NULL,
  `TimeLimit` int DEFAULT NULL,
  `TimeLimitEnforced` tinyint DEFAULT NULL,
  `AttemptsAllowed` int DEFAULT NULL,
  `PreventMovingBackwards` tinyint DEFAULT NULL,
  `AllowHints` tinyint DEFAULT NULL,
  `NotificationEmail` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DisablePagerAccess` tinyint DEFAULT NULL,
  `DisplayInCalendar` tinyint DEFAULT NULL,
  `IsAttemptRldb` tinyint DEFAULT NULL,
  `IsSubviewRldb` tinyint DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  `CategoryId` bigint DEFAULT NULL,
  `ResultId` bigint DEFAULT NULL,
  `IsRetakeIncorrectOnly` tinyint DEFAULT NULL,
  `PagingTypeId` int DEFAULT NULL,
  `IsSynchronous` tinyint DEFAULT NULL,
  `DeductionPercentage` int DEFAULT NULL,
  UNIQUE KEY `QuizId` (`QuizId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `QuizObjects_LOAD` (
  `QuizId` bigint NOT NULL,
  `QuizName` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `QuizDescription` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `QuizCategory` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IsActive` tinyint DEFAULT NULL,
  `OrgUnitId` int DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `DueDate` datetime DEFAULT NULL,
  `CreationDate` datetime DEFAULT NULL,
  `CreatedBy` bigint DEFAULT NULL,
  `LastModified` datetime DEFAULT NULL,
  `LastModifiedBy` bigint DEFAULT NULL,
  `GradeObjectId` bigint DEFAULT NULL,
  `OverallScoreCalculation` varchar(23) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `QuizScoreDenominator` decimal(19,9) DEFAULT NULL,
  `HasPassword` tinyint DEFAULT NULL,
  `IPRestricted` tinyint DEFAULT NULL,
  `TimeLimit` int DEFAULT NULL,
  `TimeLimitEnforced` tinyint DEFAULT NULL,
  `AttemptsAllowed` int DEFAULT NULL,
  `PreventMovingBackwards` tinyint DEFAULT NULL,
  `AllowHints` tinyint DEFAULT NULL,
  `NotificationEmail` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DisablePagerAccess` tinyint DEFAULT NULL,
  `DisplayInCalendar` tinyint DEFAULT NULL,
  `IsAttemptRldb` tinyint DEFAULT NULL,
  `IsSubviewRldb` tinyint DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  `CategoryId` bigint DEFAULT NULL,
  `ResultId` bigint DEFAULT NULL,
  `IsRetakeIncorrectOnly` tinyint DEFAULT NULL,
  `PagingTypeId` int DEFAULT NULL,
  `IsSynchronous` tinyint DEFAULT NULL,
  `DeductionPercentage` int DEFAULT NULL,
  UNIQUE KEY `QuizId` (`QuizId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;