CREATE TABLE `RoleDetails` (
  `RoleId` int NOT NULL,
  `RoleName` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Description` varchar(400) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IsCascading` tinyint DEFAULT NULL,
  `InClassList` tinyint DEFAULT NULL,
  `ClassListRoleName` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ClassListShowGroups` tinyint DEFAULT NULL,
  `ClassListShowSections` tinyint DEFAULT NULL,
  `ClassListDisplayRole` tinyint DEFAULT NULL,
  `AccessInactiveCO` tinyint DEFAULT NULL,
  `HasSpecialAccess` tinyint DEFAULT NULL,
  `AddToCourseOfferingGroups` tinyint DEFAULT NULL,
  `CanBeAutoEnrolledIntoGroups` tinyint DEFAULT NULL,
  `AddToCourseOfferingSections` tinyint DEFAULT NULL,
  `CanBeAutoEnrolledIntoSections` tinyint DEFAULT NULL,
  `ClassListDisplayRoleCategory` tinyint DEFAULT NULL,
  `AccessPastCourses` tinyint DEFAULT NULL,
  `AccessFutureCourses` tinyint DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  `ShowInContent` tinyint DEFAULT NULL,
  `ShowInDiscussionAssess` tinyint DEFAULT NULL,
  `ShowInDiscussionStats` tinyint DEFAULT NULL,
  `ShowInGrades` tinyint DEFAULT NULL,
  `ShowInAttendance` tinyint DEFAULT NULL,
  `AllowSelfEnrollInGroups` tinyint DEFAULT NULL,
  `ShowInRegistration` tinyint DEFAULT NULL,
  `ShowInUserProgress` tinyint DEFAULT NULL,
  `RoleAlias` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RoleCode` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LastModifiedDate` datetime DEFAULT NULL,
  `DeletedBy` int DEFAULT NULL,
  UNIQUE KEY `RoleId` (`RoleId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `RoleDetails_LOAD` (
  `RoleId` int NOT NULL,
  `RoleName` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Description` varchar(400) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IsCascading` tinyint DEFAULT NULL,
  `InClassList` tinyint DEFAULT NULL,
  `ClassListRoleName` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ClassListShowGroups` tinyint DEFAULT NULL,
  `ClassListShowSections` tinyint DEFAULT NULL,
  `ClassListDisplayRole` tinyint DEFAULT NULL,
  `AccessInactiveCO` tinyint DEFAULT NULL,
  `HasSpecialAccess` tinyint DEFAULT NULL,
  `AddToCourseOfferingGroups` tinyint DEFAULT NULL,
  `CanBeAutoEnrolledIntoGroups` tinyint DEFAULT NULL,
  `AddToCourseOfferingSections` tinyint DEFAULT NULL,
  `CanBeAutoEnrolledIntoSections` tinyint DEFAULT NULL,
  `ClassListDisplayRoleCategory` tinyint DEFAULT NULL,
  `AccessPastCourses` tinyint DEFAULT NULL,
  `AccessFutureCourses` tinyint DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  `ShowInContent` tinyint DEFAULT NULL,
  `ShowInDiscussionAssess` tinyint DEFAULT NULL,
  `ShowInDiscussionStats` tinyint DEFAULT NULL,
  `ShowInGrades` tinyint DEFAULT NULL,
  `ShowInAttendance` tinyint DEFAULT NULL,
  `AllowSelfEnrollInGroups` tinyint DEFAULT NULL,
  `ShowInRegistration` tinyint DEFAULT NULL,
  `ShowInUserProgress` tinyint DEFAULT NULL,
  `RoleAlias` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RoleCode` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LastModifiedDate` datetime DEFAULT NULL,
  `DeletedBy` int DEFAULT NULL,
  UNIQUE KEY `RoleId` (`RoleId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;