CREATE TABLE `SurveyObjects` (
  `SurveyId` bigint NOT NULL,
  `SurveyName` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CategoryId` bigint DEFAULT NULL,
  `OrgUnitId` int DEFAULT NULL,
  `Description` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DescriptionEnabled` tinyint DEFAULT NULL,
  `HasInstantFeedback` tinyint DEFAULT NULL,
  `IsAnonymous` tinyint DEFAULT NULL,
  `IsVisible` tinyint DEFAULT NULL,
  `SubmissionMessage` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Footer` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FooterIsDisplayed` tinyint DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `DisplayInCalendar` tinyint DEFAULT NULL,
  `ResultId` bigint DEFAULT NULL,
  `AttemptsAllowed` int DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  `CreatedBy` int DEFAULT NULL,
  `IsDeleted` tinyint DEFAULT NULL,
  `LastModified` datetime DEFAULT NULL,
  `LastModifiedBy` int DEFAULT NULL,
  `Version` bigint DEFAULT NULL,
  `CategoryName` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  UNIQUE KEY `SurveyId` (`SurveyId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `SurveyObjects_LOAD` (
  `SurveyId` bigint NOT NULL,
  `SurveyName` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CategoryId` bigint DEFAULT NULL,
  `OrgUnitId` int DEFAULT NULL,
  `Description` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DescriptionEnabled` tinyint DEFAULT NULL,
  `HasInstantFeedback` tinyint DEFAULT NULL,
  `IsAnonymous` tinyint DEFAULT NULL,
  `IsVisible` tinyint DEFAULT NULL,
  `SubmissionMessage` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Footer` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FooterIsDisplayed` tinyint DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `DisplayInCalendar` tinyint DEFAULT NULL,
  `ResultId` bigint DEFAULT NULL,
  `AttemptsAllowed` int DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  `CreatedBy` int DEFAULT NULL,
  `IsDeleted` tinyint DEFAULT NULL,
  `LastModified` datetime DEFAULT NULL,
  `LastModifiedBy` int DEFAULT NULL,
  `Version` bigint DEFAULT NULL,
  `CategoryName` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  UNIQUE KEY `SurveyId` (`SurveyId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;